### ISSUE TITLE
Failed to compile the example

### ISSUE THREAD

**Issue by panyfx** [photino/zino#1]
hread 'main' panicked at 'failed to read the config file `~/workplace/zino-main/examples/./config/config.dev.toml`: No such file or directory (os error 2)', /home/panda/workplace/zino-main/zino-core/src/state/mod.rs:42:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by photino** [comment]
You should run the example in the `examples/axum-app` directory.

```shell
$ cd zino-main/examples/axum-app
$ cargo run -- --env=dev
```

**Comment by panyfx** [comment]
thanks, It's ok now. but there is only running information is show as below, can you add the listening ip address and port information on the terminal?

**Comment by photino** [comment]
By default the output is in `axum/logs/`. The terminal only output warnings and errors. I will consider change `tracing::info!(env = app_env, "listen on {listener}");` to the level `WARN`.

**Comment by photino** [comment]
> thanks, It's ok now. but there is only running information shown as below, can you add the listening ip address and port information on the terminal?
> 
> Finished dev [unoptimized + debuginfo] target(s) in 1.01s Running `~/workplace/zino-main/examples/target/debug/axum-app --env=dev`

The feature has been added in the latest verstion.
