### ISSUE TITLE
Add mysql support in zino-core

### ISSUE THREAD

**Issue by superlbr** [photino/zino#35]
rt

**Comment by photino** [comment]
可以考虑提供支持 如果使用trait的泛型参数来实现 这个会比较困难

**Comment by GreenAppleOne** [comment]
强烈支持，一般公司用的都是mysql，建议支持

**Comment by photino** [comment]
在考虑了，打算把ORM再重构一下

**Comment by GreenAppleOne** [comment]
谢谢，重构ORM有时间计划吗？想未来采用这个框架做个项目，不知道时间是否来得及，另外我们这个框架经历过项目实践吗？

**Comment by photino** [comment]
在`zino-core` 0.9中初步支持了MySQL：

![image](https://github.com/photino/zino/assets/3446306/3973d5e0-b2eb-4853-bd79-b2023d9f9eec)

**Comment by photino** [comment]
Support for MySQL has been added since [zino-core 0.9](https://docs.rs/zino-core/latest/zino_core/database/index.html)

**Comment by superlbr** [comment]
是否支持多数据库配置?

**Comment by photino** [comment]
同一类型的多数据库可以，比如都是MySQL或PostgreSQL，既有MySQL又有PostgreSQL的不行
