### ISSUE TITLE
MySQL Datetime Error

### ISSUE THREAD

**Issue by akelyasir** [photino/zino#41]
Hi,

Datetime gives an error when using mysql as database structure. `error returned from database: 1292 (22007): Incorrect datetime value: '2023-05-31T12:13:31.173288613+03:00' for column `data_cube`.`dc_user`.`created_at` at row 1: 1292 (22007): Incorrect datetime value: '2023-05-31T12:13:31.173288613+03:00' for column `data_cube`.`dc_user`.`created_at` at row 1",`

Also, zino-core mysql throws an error during compilation. I added `extension::JsonObjectExt` for solution.

`use crate::{
    datetime::DateTime,
    model::{Column, DecodeRow, EncodeColumn, Query},
    request::Validation,
    extension::JsonObjectExt,
    Map, Record, SharedString,
};`

**Comment by photino** [comment]
It should compile successfully now.

**Comment by photino** [comment]
For the error 
```
error returned from database: 1292 (22007): Incorrect datetime value: '2023-05-31T12:13:31.173288613+03:00' for column `data_cube`.`dc_user`.`created_at` at row 1: 1292 (22007)
```
 What is your version of MySQL server?

**Comment by akelyasir** [comment]
MariaDB 10.5.2. It wasn't giving any errors without updating 2 days ago. It gave this error after getting your latest updates.

**Comment by photino** [comment]
The `DateTime` type was updated in `zino-core/0.9.2`. But I didn't encounter any problems when testing for MySQL v8.0.23.
`2023-05-31T12:13:31.173288613+03:00` is a valid [iso-8601](http://en.wikipedia.org/wiki/ISO_8601) datetime value, but it is not a valid [MySQL datetime literal](http://dev.mysql.com/doc/refman/5.6/en/date-and-time-literals.html), even though MySQL 8 can handle it.

**Comment by photino** [comment]
Now the `DateTime` will be formated as `2023-05-31 12:13:31.173289+0300`. It should work as expected.

**Comment by akelyasir** [comment]
Unfortunately, it gives the same error while processing. `"error returned from database: 1292 (22007): Incorrect datetime value: '**2023-05-31T19:41:45.223140748+03:00'**` but I printed the change you made and the output (**2023-05-31 19:44:30.001451634+0300**) is correct. I'll check and post why the change wasn't applied even though I recreated the tables.

**Comment by akelyasir** [comment]
Hi @photino  I uninstalled MariaDB and installed mysql version 8.0 and it's working now. I couldn't figure out what kind of problem there was with Mariadb. 

Thanks for your interest.

**Comment by photino** [comment]
@akelyasir Does MariaDB support `select TIMESTAMP'2023-05-31 20:25:06.189499 +0800';`? If so, we can use this format for serialization.

**Comment by akelyasir** [comment]
@photino I did a few tries and figured out the problem with mariadb. The problem is solved when we remove `**%z**` and set the format to "`**%Y-%m-%d %H:%M:%S%.6f**`". Is this format acceptable for general use?

**Comment by akelyasir** [comment]
@photino Also, I had a question. Will a work be migrated to reflect model changes in the database?

**Comment by photino** [comment]
Yes, we should remove the `%z` for serialization, which is enough to support MariaDB. But for `to_string()`, we should keep the timezone info.

At present, when the model changes, we need alert the table definition manually. It is somewhat complex for the ORM to determine what to do when the table already has data.

**Comment by akelyasir** [comment]
@photino `to_string()` I didn't make any changes to it. 

I am aware of the complexity, I hope I can contribute. Thank you for your interest and help.
