### ISSUE TITLE
Run the framework in the stable Rust

### ISSUE THREAD

**Issue by photino** [photino/zino#51]
We are wating for the stablization of the following features:

* [~~Tracking Issue for async_fn_in_trait, return_position_impl_trait_in_trait~~](https://github.com/rust-lang/rust/issues/91611)
* [Tracking Issue for lazy_cell](https://github.com/rust-lang/rust/issues/109736)
* [Tracking issue for eRFC 2497, "if- and while-let-chains, take 2"](https://github.com/rust-lang/rust/issues/53667)
* [~~Tracking Issue for result_option_inspect~~](https://github.com/rust-lang/rust/issues/91345)
* [Tracking issue for #[doc(cfg(…))], #[doc(cfg_hide(…))] and doc_auto_cfg](https://github.com/rust-lang/rust/issues/43781)
* [Tracking issue for RFC 2532, "Associated type defaults"](https://github.com/rust-lang/rust/issues/29661)
* [Tracking issue: declarative macros 2.0](https://github.com/rust-lang/rust/issues/39412)
* [~~Tracking Issue for Iterator::intersperse~~](https://github.com/rust-lang/rust/issues/79524)
* [Tracking Issue for slice_first_last_chunk feature](https://github.com/rust-lang/rust/issues/111774)
* [Tracking issue for Vec::extract_if and LinkedList::extract_if](https://github.com/rust-lang/rust/issues/43244)

**Comment by epenabella** [comment]
yes!

**Comment by photino** [comment]
We will consider using stable rustc when the `async-fn-in-trait` feature has been stabilized in 1.76.

**Comment by photino** [comment]
The latest version can run in the stable rust 1.75 now.
