### ISSUE TITLE
Is the framework ready for enterprise-level production?

### ISSUE THREAD

**Issue by andeya** [photino/zino#53]

**Comment by photino** [comment]
The framework has already been applied to some enterprise-level projects. It works quite well in practice. Any bug reports or feature requirements are welcome!

However, the framework has not reached a stage of 1.0. So the full backwards-compatibility is not guaranteed, but we will try our best to follow the semantic versioning.

We should also note that the framework requires nightly rustc to run. We will consider using stable rustc when the `async-fn-in-trait` feature has been stabilized in 1.76.

**Comment by andeya** [comment]
Good!
