### ISSUE TITLE
tauri可以用这个框架吗

### ISSUE THREAD

**Issue by 107295472** [photino/zino#57]

**Comment by photino** [comment]
tauri还不能，主要是tauri中没有`Router`结构体（由前端处理），没办法实现我们zino框架的`Application` 本来可以为`tauri::Builder`实现`Application`，但是`invoke_handler`接受的却不是一个具体的类型，那就没办法了

**Comment by 107295472** [comment]
哦，那就是做后端服务可以用

**Comment by photino** [comment]
也不是只能做后端服务 dioxus也能做桌面开发、Web端、移动端
